version: '3.8'
services:
  subscriber_app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: subscriber_app
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      DATA_PUBLISH_INTERVAL_SECONDS: ${DATA_PUBLISH_INTERVAL_SECONDS}
      DATA_COLLECT_INTERVAL_SECONDS: ${DATA_COLLECT_INTERVAL_SECONDS}
      MQTT_TOPIC: ${MQTT_TOPIC}
      BROKER_ADDRESS: ${BROKER_ADDRESS}
    volumes:
      - ./app:/app
      - /sys/class/gpio:/sys/class/gpio
